### ISSUE TITLE
license

### ISSUE THREAD

**Issue by flosse** [rasendubi/bkernel#1]
Would you mind to add a license file?
(and you may create a PR for [rust-os-comparison](https://github.com/flosse/rust-os-comparison) with basic information.)

**Comment by zetok** [comment]
Hmm, looks like one file is licensed under something that looks like a modified BSD, with added clause that the code can be used only on/for devices produced by the company that wrote the code.. https://github.com/rasendubi/bkernel/blob/3bd7d7a747f30a190cbd79f704dfff11cc04c11b/src/bootstrap.s

As for license of the project - any chances for GPL?
